---
# Define which datasets are in which corpora
corpora:

  white_supremacist_train:
    create: False
    datasets:  # any unique name, source, or domain is its own
      - name: qian2018
        source: twitter
        domain: tweet
        load_paths:
          - ../data/qian2018/data.jsonl
      - name: elsherief2021
        source: twitter
        domain: tweet
        load_paths:
          - ../data/elsherief2021/data.jsonl
          - ../data/elsherief2021/users.jsonl
          - ../data/qian2018/users.jsonl
          - /storage2/mamille3/data/hate_speech/elsherief2021/implicit_hate_v1_stg2_posts.tsv
      - name: patriotfront
        source: discord
        domain: chat
        load_paths:
          - /storage2/mamille3/data/patriotfront/2017-Vanguard_America-Patriot_Front/Discord/dump
          - /storage2/mamille3/data/patriotfront/2018/Discord/dump_Front_And_Center
          - /storage2/mamille3/data/patriotfront/2018/Discord/dump_MI_Goy_Scouts_Official
          - ../resources/us_first_names_1990.csv
      - name: ironmarch
        source: ironmarch
        domain: forum
        load_paths:
          - ../data/iron_march_201911/csv/core_search_index.csv
      - name: stormfront
        source: stormfront
        domain: forum
        load_paths:
          - ../data/stormfront_archive/processed
      - name: jokubausaite2020
        source: 4chan
        domain: forum
        load_paths:
          - /storage2/mamille3/data/4chan/jokubausaite2020/
      - name: papasavva2020
        source: 4chan
        domain: forum
        load_paths:
          - ../data/papasavva2020_white_supremacist_flag_posts.csv
          - /storage2/mamille3/data/4chan/jokubausaite2020/
      - name: calderon2021
        source: daily_stormer
        domain: long-form
        load_paths:
          - ../data/calderon2021/d_stormer_documents.json
      - name: calderon2021
        source: american_renaissance
        domain: long-form
        load_paths:
          - ../data/calderon2021/amran_documents.json
      - name: pruden2022
        source: breivik_manifesto
        domain: long-form
        load_paths:
          - ../data/pruden2022/AndersBehringBreivikManifesto.txt
      - name: pruden2022
        source: powell_rivers_of_blood_speech
        domain: long-form
        load_paths:
          - '../data/pruden2022/Enoch-Powells-Rivers-of-Blood-new-analysis-pdf.txt'
      - name: pruden2022
        source: raspail_camp_of_the_saints_book
        domain: long-form
        load_paths:
          - '../data/pruden2022/Jean-Raspail-Camp-of-the-Saints.txt'
      - name: pruden2022
        source: lane_white_genocide_manifesto
        domain: long-form
        load_paths:
          - '../data/pruden2022/Lane_White Genocide Manifesto.txt'
      - name: pruden2022
        source: camus_the_great_replacement_book
        domain: long-form
        load_paths:
          - '../data/pruden2022/Renaud Camus - The Great Replacement - Part I-RWTS (2012).txt'

  neutral_train:
    create: False
    datasets:
      - name: reddit_match
        source: reddit
        domain: forum
        load_paths: 
          - '../data/neutral/reddit_comments'
      - name: discord_match
        source: discord
        domain: chat
        load_paths: 
          - '/storage2/mamille3/data/discord/v3/content/drive/Shareddrives/Datasets/cleaned-v4/discord-v3'
      - name: news_match
        source: news
        domain: long-form
        load_paths: 
          - '/storage2/mamille3/data/news/now2010-2021/text'
      - name: twitter_match
        source: twitter
        domain: tweet
        load_paths: 
          - '/storage2/mamille3/white_supremacist_lang/data/neutral/twitter/'
    ref_corpus_name: 'white_supremacist_train'

  annotated_test: # test sets human-annotated for white supremacy
    create: False
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'
      #- name: siegel2021 
      #  source: twitter
      #  domain: tweet
      #  load_paths:
      #    - '../data/siegel2021/white_nationalist_training_data.csv'


experiment: # define experiments where train particular classifiers on particular sets of training and testing corpora
  train: False
  test: True
  train_pos: white_supremacist_train
  train_neg: neutral_train
  test_corpus: annotated_test
  classifier: 
    type: bert
    load: '../models/bert/checkpoint-778326' # Null to train a new model from scratch, or a path to the model to load
