---
# Define which datasets are in which corpora
corpora:

  white_supremacist_train:
    create: False
    label: white_supremacist
    min_word_limit: 10
    lda_filter: # remove posts that match certain topics in a trained LDA model. Put Null if not using
      #query: 'domain=="forum"'
      query: Null
      model: '../models/white_supremacist_fulltext_lda30.pkl'
      vectorizer: '../models/white_supremacist_fulltext_countvectorizer.pkl'
      include_topics: [13,28]
      exclude_topics: Null
    sample: # Put Null if not using
      query: 'domain=="forum"' # query to select data
      sample_n: 100000 # n to sample from that queried data 
    datasets:  # any unique name, source, or domain is its own
      - name: qian2018
        source: twitter
        domain: tweet
        load_paths:
          - ../data/qian2018/data.jsonl
      - name: elsherief2021
        source: twitter
        domain: tweet
        load_paths:
          - ../data/elsherief2021/data.jsonl
          - ../data/elsherief2021/users.jsonl
          - ../data/qian2018/users.jsonl
          - /storage2/mamille3/data/hate_speech/elsherief2021/implicit_hate_v1_stg2_posts.tsv
      - name: patriotfront
        source: discord
        domain: chat
        load_paths:
          - /storage2/mamille3/data/patriotfront/2017-Vanguard_America-Patriot_Front/Discord/dump
          - /storage2/mamille3/data/patriotfront/2018/Discord/dump_Front_And_Center
          - /storage2/mamille3/data/patriotfront/2018/Discord/dump_MI_Goy_Scouts_Official
          - ../resources/us_first_names_1990.csv
      - name: ironmarch
        source: ironmarch
        domain: forum
        load_paths:
          - ../data/iron_march_201911/csv/core_search_index.csv
      - name: stormfront
        source: stormfront
        domain: forum
        load_paths:
          - ../data/stormfront_archive/processed
      - name: jokubausaite2020
        source: 4chan
        domain: forum
        load_paths:
          - /storage2/mamille3/data/4chan/jokubausaite2020/
      - name: papasavva2020
        source: 4chan
        domain: forum
        load_paths:
          - ../data/papasavva2020_white_supremacist_flag_posts.csv
          - /storage2/mamille3/data/4chan/jokubausaite2020/
      - name: calderon2021
        source: daily_stormer
        domain: long-form
        load_paths:
          - ../data/calderon2021/d_stormer_documents.json
      #- name: calderon2021
      #  source: american_renaissance
      #  domain: long-form
      #  load_paths:
      #    - ../data/calderon2021/amran_documents.json
      - name: pruden2022
        source: breivik_manifesto
        domain: long-form
        load_paths:
          - ../data/pruden2022/AndersBehringBreivikManifesto.txt
      - name: pruden2022
        source: powell_rivers_of_blood_speech
        domain: long-form
        load_paths:
          - '../data/pruden2022/Enoch-Powells-Rivers-of-Blood-new-analysis-pdf.txt'
      - name: pruden2022
        source: raspail_camp_of_the_saints_book
        domain: long-form
        load_paths:
          - '../data/pruden2022/Jean-Raspail-Camp-of-the-Saints.txt'
      - name: pruden2022
        source: lane_white_genocide_manifesto
        domain: long-form
        load_paths:
          - '../data/pruden2022/Lane_White Genocide Manifesto.txt'
      - name: pruden2022
        source: camus_the_great_replacement_book
        domain: long-form
        load_paths:
          - '../data/pruden2022/Renaud Camus - The Great Replacement - Part I-RWTS (2012).txt'

  neutral_train:
    create: False
    label: neutral
    min_word_limit: 1
    datasets:
      - name: reddit_match
        source: reddit
        domain: forum
        load_paths: 
          - '../data/neutral/reddit_comments'
      - name: discord_match
        source: discord
        domain: chat
        load_paths: 
          - '/storage2/mamille3/data/discord/v3/content/drive/Shareddrives/Datasets/cleaned-v4/discord-v3'
      - name: news_match
        source: news
        domain: long-form
        load_paths: 
          - '/storage2/mamille3/data/news/now2010-2021/text'
      - name: twitter_match
        source: twitter
        domain: tweet
        load_paths: 
          - '/storage2/mamille3/white_supremacist_lang/data/neutral/twitter/'
    ref_corpora: 
      - 'white_supremacist_train'

  neutral_antiracist_size: # all neutral, but size of neutral + antiracist corpus
    create: False
    label: neutral
    min_word_limit: 1
    datasets:
      - name: twitter_match
        source: twitter
        domain: tweet
        load_paths: 
          - '../data/neutral/twitter/'
      - name: discord_match
        source: discord
        domain: chat
        load_paths: 
          - '../../data/discord/v3/content/drive/Shareddrives/Datasets/cleaned-v4/discord-v3'
      - name: reddit_match
        source: reddit
        domain: forum
        load_paths: 
          - '../data/neutral/reddit_comments'
      - name: news_match
        source: news
        domain: long-form
        load_paths: 
          - '../../data/news/now2010-2021/text'
    ref_corpora: 
      - 'white_supremacist_train'
    match_factor: 1.5 # factor to multiply even sample with reference corpus by


  antiracist_train:
    create: False
    label: antiracist
    min_word_limit: 1
    datasets:
      - name: reddit_antiracist
        source: reddit
        domain: forum
        load_paths: 
          - '../data/antiracist/reddit_comments'
      - name: twitter_antiracist
        source: twitter
        domain: tweet
        load_paths: 
          - '../data/antiracist/twitter/'
      - name: medium_antiracist
        source: medium
        domain: long-form
        load_paths: 
          - '../data/antiracist/medium'
    ref_corpora: 
      - 'white_supremacist_train'
      - 'neutral_train'

  annotated: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    test_size: 0.3
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'
      - name: siegel2021 
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'
      #- name: siegel2021_white_nationalist_only
      #  source: twitter
      #  domain: tweet
      #  load_paths:
      #    - '../data/siegel2021/white_nationalist_training_data.csv'
      #    - '../data/siegel2021/hate_speech_training_data.csv'
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_5x: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral, -1: neutral} # -1 in lda_annotations
    test_size: 0.3 # fraction of samples to include in a test split
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'
      - name: siegel2021_white_nationalist_only
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'
      - name: lda_annotations
        source: 4chan # is majority, but has a mix
        domain: forum # is majority, but has a mix
        load_paths:
          - '../data/white_supremacist_annotations_30topics.csv'

  #annotated_alatawi2021: # just alatawi2021 for training
  #  create: False
  #  label: {1: white_supremacist, 0: neutral}
  #  test_size: 0.3
  #  datasets:
  #    - name: alatawi2021
  #      source: twitter
  #      domain: tweet
  #      load_paths:
  #        - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'

  #annotated_rieger2021: # just rieger2021 for training
  #  create: False
  #  label: {1: white_supremacist, 0: neutral}
  #  test_size: 0.3
  #  datasets:
  #    - name: rieger2021
  #      source: 4chan # actually is reddit, 4chan and 8chan (could separate)
  #      domain: forum
  #      load_paths:
  #        - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
  #        - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  #annotated_lda: # my personal annotations of white supremacist corpus examples, by LDA topioc
  #  create: False
  #  label: {1: white_supremacist, 0: neutral, -1: neutral}
  #  datasets:
  #    - name: lda_annotations
  #      source: 4chan # is majority, but has a mix
  #      domain: forum # is majority, but has a mix
  #      load_paths:
  #        - '../data/white_supremacist_annotations_30topics.csv'

  annotated_siegel2021:
    create: False
    label: {1: white_supremacist, 0: neutral}
    datasets:
      - name: siegel2021_white_nationalist_only
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'

  annotated_alatawi2021:
    create: False
    label: {1: white_supremacist, 0: neutral}
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'

  annotated_rieger2021:
    create: False
    label: {1: white_supremacist, 0: neutral}
    datasets:
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_alatawi2021_5x: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'

  annotated_siegel2021_5x: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: siegel2021_white_nationalist_only
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'

  annotated_rieger2021_5x: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_lda_5x: # my personal annotations of white supremacist corpus examples, by LDA topioc
    create: False
    label: {1: white_supremacist, 0: neutral, -1: neutral}
    sample:
      sample_factor: 5
    datasets:
      - name: lda_annotations
        source: 4chan # is majority, but has a mix
        domain: forum # is majority, but has a mix
        load_paths:
          - '../data/white_supremacist_annotations_30topics.csv'

  annotated_5x_train70_singles: # created in corpus_stats.ipynb, load-only
    create: False
    label: {1: white_supremacist, 0: neutral}

  annotated_lda: # my personal annotations of white supremacist corpus examples, by LDA topioc
    create: False
    label: {1: white_supremacist, 0: neutral, -1: neutral}
    datasets:
      - name: lda_annotations
        source: 4chan # is majority, but has a mix
        domain: forum # is majority, but has a mix
        load_paths:
          - '../data/white_supremacist_annotations_30topics.csv'

  domain_test: # out-of-domain evaluations
    create: False
    label: white_supremacist
    datasets:
      - name: adl_heatmap
        source: adl_heatmap
        domain: offline_propaganda
        load_paths:
          - '../data/adl_heatmap/adl_quotes.csv'
          - '../data/adl_heatmap/adl_heatmap_2022-10-27.csv'

  bias_test:
    create: False
    label: neutral # possibly antiracist for positive uses of identities?
    datasets:
      - name: hatecheck_identity_nonhate
        source: hatecheck
        domain: synthetic
        load_paths:
          - '../../data/hate_speech/hatecheck-data/test_suite_cases.csv'


experiment: # define experiments where train particular classifiers on particular sets of training and testing corpora
  name: 3way_2topic_23877_test
  train: False
  test: True
  train_corpora: # Still needed for eval runs to get ID to label mappings
    - name: white_supremacist_train
    #- name: neutral_antiracist_size
    - name: neutral_train
    - name: antiracist_train
    #- name: annotated_5x
    #  fold: train
    #- name: annotated
    #  fold: train
    #- name: annotated_alatawi2021_5x
    #- name: annotated_rieger2021_5x
    #- name: annotated_siegel2021_5x
    #- name: annotated_lda_5x
  test_corpora: 
    #- name: annotated_alatawi2021
    #- name: annotated_siegel2021
    #- name: annotated_rieger2021
    #- name: annotated_5x
    #  fold: test
    - name: annotated
    - name: domain_test
    - name: bias_test
  test_label_combine: {antiracist: neutral}
  classifier: 
    type: bert
    n_epochs: 8
    #load: Null # Null to train a new model from scratch, or a path to the model to load
    load: '../output/bert/3way_2topic/checkpoint-23877'
