---
# Define which datasets are in which corpora
corpora:

  annotated: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'
      - name: siegel2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'
      #- name: siegel2021_white_nationalist_only # Probably put in separate corpus to eval
      #  source: twitter
      #  domain: tweet
      #  load_paths:
      #    - '../data/siegel2021/white_nationalist_training_data.csv'
      #    - '../data/siegel2021/hate_speech_training_data.csv'
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_alatawi2021:
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'

  annotated_rieger2021:
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    datasets:
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_siegel2021:
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    datasets:
      - name: siegel2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'

  annotated_alatawi2021_5x: # test sets human-annotated for white supremacy
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'

  annotated_rieger2021_5x: # test sets human-annotated for white supremacy
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'

  annotated_siegel2021_5x: # test sets human-annotated for white supremacy
    create: True
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: siegel2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'

  annotated_5x: # test sets human-annotated for white supremacy
    create: False
    label: {1: white_supremacist, 0: neutral}
    split:
      test_size: 0.3
      split_ref: annotated # split based on a prior corpus's train/test split
    sample:
      sample_factor: 5 # factor to multiply the sample by (for training fold if split)
    datasets:
      - name: alatawi2021
        source: twitter
        domain: tweet
        load_paths:
          - '../data/alatawi2021_white_supremacist_annotated_tweets.csv'
      - name: siegel2021 
        source: twitter
        domain: tweet
        load_paths:
          - '../data/siegel2021/white_nationalist_training_data.csv'
          - '../data/siegel2021/hate_speech_training_data.csv'
      #- name: siegel2021_white_nationalist_only
      #  source: twitter
      #  domain: tweet
      #  load_paths:
      #    - '../data/siegel2021/white_nationalist_training_data.csv'
      #    - '../data/siegel2021/hate_speech_training_data.csv'
      - name: rieger2021
        source: 4chan # actually is reddit, 4chan and 8chan (could separate)
        domain: forum
        load_paths:
          - '../../data/hate_speech/rieger2021/Datensatz mit mf_ide2.csv'
          - '../../data/hate_speech/rieger2021/Kiening_Kommentare.xlsx'


experiment: # define experiments where train particular classifiers on particular sets of training and testing corpora
  name: Null
  train: False
  test: False
  train_corpora: # could specify a flag in the corpora, but that's not really about the corpus
    - name: white_supremacist_train
    - name: neutral_train
    - name: antiracist_train
    - name: annotated_5x
      fold: train
    - name: annotated_lda_5x
  test_corpora: 
    - name: annotated_5x
      fold: test
    - name: domain_test
    - name: bias_test
  classifier: 
    type: bert
    n_epochs: 10
    load: Null # Null to train a new model from scratch, or a path to the model to load
    #load: '../output/bert/checkpoint-778326' # Null to train a new model from scratch, or a path to the model to load
